services:
  backend:
    build:
      context: ./Sudoku-Solver
    command: gunicorn sudoku_solver.wsgi --bind 0.0.0.0:8000
    ports: 
      - '8000:8000'

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - ./Sudoku-Solver/static:/usr/share/nginx/html:ro
    depends_on:
      - backend